"""Scope classification for every registered API route (U1).

The manifest is the isolation contract: `tests/api/test_scope_manifest.py` fails
when a route is added without a classification here, or when an entry goes
stale. The isolation suites parametrise over these classes.

Classes:
- public        no authentication
- auth          credential endpoints
- school-scoped staff routes acting inside one named school
- driver-scoped resolved through the driver's own membership and bus
- parent-linked resolved through the parent's accepted child links
- user-scoped   per-account surfaces (push, notification feed), any role
- provider-global  Kuumbai-only cross-school surfaces (arrives with U10)
"""

MANIFEST: dict[tuple[str, str], str] = {
    ("GET", "/api/health"): "public",
    ("POST", "/api/auth/signup"): "auth",
    ("POST", "/api/auth/login"): "auth",
    ("POST", "/api/auth/pin-login"): "auth",
    ("POST", "/api/auth/totp"): "auth",
    ("POST", "/api/auth/logout"): "auth",
    ("GET", "/api/auth/me"): "auth",
    ("POST", "/api/auth/forgot-password"): "auth",
    ("POST", "/api/auth/reset-password"): "auth",
    ("POST", "/api/auth/change-password"): "auth",
    ("POST", "/api/auth/offers/{offer_id}/accept"): "auth",
    ("POST", "/api/auth/offers/{offer_id}/decline"): "auth",
    ("GET", "/api/auth/dev/last-reset-link"): "auth",
    ("GET", "/api/fleet/buses"): "school-scoped",
    ("POST", "/api/fleet/buses"): "school-scoped",
    ("PUT", "/api/fleet/buses/{bus_id}"): "school-scoped",
    ("DELETE", "/api/fleet/buses/{bus_id}"): "school-scoped",
    ("GET", "/api/fleet/schools"): "school-scoped",
    ("GET", "/api/fleet/school"): "school-scoped",
    ("PUT", "/api/fleet/schools/{school_id}"): "school-scoped",
    ("GET", "/api/fleet/routes"): "school-scoped",
    ("POST", "/api/fleet/routes"): "school-scoped",
    ("PUT", "/api/fleet/routes/{route_id}"): "school-scoped",
    ("DELETE", "/api/fleet/routes/{route_id}"): "school-scoped",
    ("PUT", "/api/fleet/routes/{route_id}/stops/{student_id}"): "school-scoped",
    ("DELETE", "/api/fleet/routes/{route_id}/stops/{student_id}"): "school-scoped",
    ("PUT", "/api/fleet/routes/{route_id}/stop-order"): "school-scoped",
    ("POST", "/api/fleet/routes/{route_id}/recalculate"): "school-scoped",
    ("POST", "/api/fleet/routes/{route_id}/broadcast"): "school-scoped",
    ("POST", "/api/fleet/geocode"): "school-scoped",
    ("POST", "/api/fleet/reverse-geocode"): "school-scoped",
    ("GET", "/api/fleet/places/suggest"): "school-scoped",
    ("GET", "/api/fleet/places/details"): "school-scoped",
    ("POST", "/api/fleet/route-options"): "school-scoped",
    ("POST", "/api/fleet-plans/confirm-fleet"): "school-scoped",
    ("POST", "/api/fleet-plans/draft"): "school-scoped",
    ("GET", "/api/fleet-plans/current"): "school-scoped",
    ("GET", "/api/fleet-plans/review"): "school-scoped",
    ("POST", "/api/fleet-plans/{plan_id}/move"): "school-scoped",
    ("POST", "/api/fleet-plans/{plan_id}/reorder"): "school-scoped",
    ("POST", "/api/fleet-plans/{plan_id}/pin"): "school-scoped",
    ("POST", "/api/fleet-plans/{plan_id}/pattern"): "school-scoped",
    ("POST", "/api/fleet-plans/{plan_id}/assign"): "school-scoped",
    ("POST", "/api/fleet-plans/{plan_id}/resolve"): "school-scoped",
    ("POST", "/api/fleet-plans/{plan_id}/apply"): "school-scoped",
    ("POST", "/api/fleet-plans/{plan_id}/restore"): "school-scoped",
    ("POST", "/api/fleet-plans/{plan_id}/discard"): "school-scoped",
    ("GET", "/api/fleet-plans/slot-ins"): "school-scoped",
    ("POST", "/api/fleet-plans/slot-ins/accept"): "school-scoped",
    ("POST", "/api/fleet-plans/slot-ins/dismiss"): "school-scoped",
    ("GET", "/api/students"): "school-scoped",
    ("POST", "/api/students"): "school-scoped",
    ("PUT", "/api/students/{student_id}"): "school-scoped",
    ("DELETE", "/api/students/{student_id}"): "school-scoped",
    ("POST", "/api/students/bulk/validate"): "school-scoped",
    ("POST", "/api/students/bulk"): "school-scoped",
    ("GET", "/api/students/pin-map"): "school-scoped",
    ("GET", "/api/students/absences"): "school-scoped",
    ("POST", "/api/students/absences"): "school-scoped",
    ("DELETE", "/api/students/absences/{absence_id}"): "school-scoped",
    ("GET", "/api/runs"): "school-scoped",
    ("POST", "/api/runs"): "school-scoped",
    ("PUT", "/api/runs/{run_id}"): "school-scoped",
    ("DELETE", "/api/runs/{run_id}"): "school-scoped",
    ("POST", "/api/runs/{run_id}/force-close"): "school-scoped",
    ("POST", "/api/runs/{run_id}/contacted"): "school-scoped",
    ("GET", "/api/runs/{run_id}/report"): "school-scoped",
    ("GET", "/api/runs/driver/context"): "driver-scoped",
    ("POST", "/api/runs/driver/start"): "driver-scoped",
    ("POST", "/api/runs/driver/arrive"): "driver-scoped",
    ("POST", "/api/runs/driver/end"): "driver-scoped",
    ("POST", "/api/runs/driver/boarding"): "driver-scoped",
    ("POST", "/api/runs/driver/dropoff"): "driver-scoped",
    ("POST", "/api/runs/driver/handover"): "driver-scoped",
    ("POST", "/api/runs/driver/reverse"): "driver-scoped",
    ("POST", "/api/runs/driver/absent"): "driver-scoped",
    ("GET", "/api/incidents"): "school-scoped",
    ("GET", "/api/incidents/unread-count"): "school-scoped",
    ("GET", "/api/incidents/today-count"): "school-scoped",
    ("POST", "/api/incidents/driver"): "driver-scoped",
    ("POST", "/api/incidents/{incident_id}/acknowledge"): "school-scoped",
    ("DELETE", "/api/incidents/{incident_id}"): "school-scoped",
    ("GET", "/api/accounts/drivers"): "school-scoped",
    ("POST", "/api/accounts/drivers"): "school-scoped",
    ("PUT", "/api/accounts/drivers/{driver_id}"): "school-scoped",
    ("DELETE", "/api/accounts/drivers/{driver_id}"): "school-scoped",
    ("GET", "/api/accounts/parents"): "school-scoped",
    ("PUT", "/api/accounts/parents/{parent_id}"): "school-scoped",
    ("DELETE", "/api/accounts/parents/{parent_id}"): "school-scoped",
    ("GET", "/api/staff"): "school-scoped",
    ("POST", "/api/staff"): "school-scoped",
    ("DELETE", "/api/staff/{user_id}"): "school-scoped",
    ("DELETE", "/api/staff/offers/{offer_id}"): "school-scoped",
    ("POST", "/api/staff/{user_id}/reset-password"): "school-scoped",
    ("GET", "/api/provider/schools"): "provider-global",
    ("POST", "/api/provider/schools"): "provider-global",
    ("POST", "/api/provider/step-in"): "provider-global",
    ("POST", "/api/provider/step-out"): "provider-global",
    ("GET", "/api/provider/audit"): "provider-global",
    ("GET", "/api/provider/accounts"): "provider-global",
    ("POST", "/api/provider/accounts"): "provider-global",
    ("DELETE", "/api/provider/accounts/{user_id}"): "provider-global",
    ("POST", "/api/provider/accounts/{user_id}/reset-totp"): "provider-global",
    ("POST", "/api/provider/totp/enrol"): "provider-global",
    ("POST", "/api/provider/totp/confirm"): "provider-global",
    ("GET", "/api/parent-portal/children"): "parent-linked",
    ("GET", "/api/parent-portal/track"): "parent-linked",
    ("GET", "/api/parent-portal/alerts"): "parent-linked",
    ("GET", "/api/parent-portal/profile"): "parent-linked",
    ("POST", "/api/parent-portal/cancel-ride"): "parent-linked",
    ("DELETE", "/api/parent-portal/cancel-ride"): "parent-linked",
    ("GET", "/api/parent-portal/pending"): "parent-linked",
    ("POST", "/api/parent-portal/pending/{school_id}/accept"): "parent-linked",
    ("POST", "/api/parent-portal/pending/{school_id}/decline"): "parent-linked",
    ("GET", "/api/push/config"): "public",
    ("POST", "/api/push/subscribe"): "user-scoped",
    ("POST", "/api/push/unsubscribe"): "user-scoped",
    ("POST", "/api/push/fcm-token"): "user-scoped",
    ("POST", "/api/push/fcm-token/unregister"): "user-scoped",
    ("GET", "/api/push/notifications"): "user-scoped",
    ("GET", "/api/push/notifications/unread-count"): "user-scoped",
    ("POST", "/api/push/notifications/mark-read"): "user-scoped",
}
